name: Python application

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    branches: [main]
    types:
    - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME2: "challenge22" # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH2: 'challenge2/app' # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_NAME3: "challenge32-cuuw" # TODO: figure out how to query this from active state
  AZURE_WEBAPP_PACKAGE_PATH3: 'ratings_api/' # set this to the path to your web app project, defaults to the repository root

jobs:
  build_challenge2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH2 }}
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME2 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH2 }}
    - name: logout
      run: |
        az logout

  build_challenge3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH3 }}
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME3 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH3 }}
    - name: logout
      run: |
        az logout